services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped

  web:
    build: .
    env_file: .env
    depends_on:
      - redis
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./output:/app/output
    command: flask run --host=0.0.0.0

  worker:
    build: .
    env_file: .env
    depends_on:
      - web
      - redis
    volumes:
      - .:/app
      - ./data:/app/data
      - ./output:/app/output
    command: celery -A app.celery.celery_app.celery worker --pool=solo --loglevel=info

